spring.application.name=api
# spring.application.name=api-bakery
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/sms_db
# spring.datasource.url=jdbc:postgres://salim:VCvCK31b7C2NjW0BehblLUlmxpKrs8wH@dpg-coc8d18l5elc739osp0g-a/airfox
spring.datasource.password=825356
# spring.datasource.password=VCvCK31b7C2NjW0BehblLUlmxpKrs8wH
spring.datasource.username=postgres
# spring.datasource.username=salim
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Email configuration
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=
# spring.mail.password=
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true